<a href="https://colab.research.google.com/github/bilal444hammas/ASSIGNMENT-CH6/blob/master/Assignment_Ch_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Download Following Dataset and use five text(use randomly generated 5 numbers and extract the data of the generated numbers from the dataset) to test the assignments. https://www.kaggle.com/bittlingmayer/amazonreviews

1) one-hot coding of the following data using book codes (naive codes) of listing 6.1.

2) Also, provide one-hot coding using Keras built-in function (listing 6.3).

3) provide one-hot coding with hashing (listing 6.4)

4) Validate the how much they are similar. Try to maximize the similarity (ideally should be 100% the same). Specify the reason if both are not the same.

5) Try to implement word-embedding using code given in listing (6.7) and shared with me the embedding array as well as the word dictionary.

6) From 6.8 code pre-trained word-embeddings

7) Apply RNN to the given text (listing 6.21) and provide output 8) Match the results of RNN (step 7) with the step 5 and also with step 6. Share the output of the analysis. Submit your assignment here https://forms.gle/ta88MoyAC8Fmsd4n7


In [0]:
with open("/content/drive/My Drive/train.ft.txt") as myfile:
    firstNlines=myfile.readlines()[0:5]

In [0]:
print(firstNlines)

['__label__2 Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^\n', "__label__2 The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny.\n", '__label__2 Amazing!: This sou

## #Listing 6.1 Word-level one-hot encoding (toy example)

In [0]:
#Listing 6.1 Word-level one-hot encoding (toy example)
import numpy as np
samples = firstNlines
token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
max_length = 10
results = np.zeros(shape=(len(samples),max_length,max(token_index.values()) + 1))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.

In [0]:
print(results)

[[[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


### listing 6.3

In [0]:
#listing 6.3
from tensorflow.keras.preprocessing.text import Tokenizer
samples =  firstNlines
tokenizer = Tokenizer(num_words=1000)#Creates a tokenizer, configured to only take into account the 1,000 most common words
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
sequences

[[15,
  16,
  72,
  29,
  21,
  1,
  73,
  74,
  5,
  75,
  76,
  77,
  78,
  6,
  79,
  1,
  80,
  30,
  38,
  81,
  39,
  40,
  4,
  22,
  82,
  6,
  29,
  9,
  83,
  31,
  84,
  85,
  10,
  7,
  4,
  23,
  13,
  1,
  10,
  24,
  25,
  41,
  86,
  3,
  26,
  3,
  1,
  87,
  4,
  23,
  42,
  13,
  6,
  88,
  1,
  14,
  7,
  6,
  89,
  90,
  91,
  92,
  93,
  2,
  94,
  11,
  95,
  96,
  97,
  98,
  99,
  2,
  100,
  101,
  6,
  22,
  102,
  103,
  31,
  104,
  9,
  105],
 [15,
  16,
  1,
  14,
  12,
  42,
  9,
  106,
  43,
  107,
  11,
  108,
  3,
  109,
  110,
  17,
  5,
  8,
  1,
  14,
  111,
  112,
  2,
  4,
  113,
  17,
  114,
  115,
  11,
  116,
  9,
  117,
  11,
  118,
  5,
  30,
  18,
  119,
  8,
  44,
  120,
  121,
  122,
  1,
  7,
  8,
  123,
  2,
  43,
  45,
  124,
  9,
  6,
  21,
  46,
  125,
  2,
  126,
  127,
  128,
  129,
  9,
  130,
  1,
  47,
  131,
  19,
  5,
  8,
  132,
  133,
  4,
  134,
  48,
  41,
  20,
  32,
  27,
  135,
  9,
  49,
  136,
  137,
  21,
  5,
  138,

In [0]:
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary') #for make matrix one hot coding
print(one_hot_results)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [0]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 262 unique tokens.


## #Listing 6.4 Word-level one-hot encoding with hashing trick (toy example)

In [0]:
#Listing 6.4 Word-level one-hot encoding with hashing trick (toy example)
samples = firstNlines
dimensionality = 1000
max_length = 10
results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1.

In [0]:
print(results)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [0]:
with open("/content/drive/My Drive/train.ft.txt") as myfile:
    lines=myfile.readlines()[0:2000]

In [0]:
lines

['__label__2 Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^\n',
 "__label__2 The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny.\n",
 '__label__2 Amazing!: This s

In [0]:
import numpy as np
samples = lines
token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
max_length = 10
results = np.zeros(shape=(len(samples),max_length,max(token_index.values()) + 1))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.

In [0]:
print(results)

[[[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer
samples =  lines
tokenizer = Tokenizer(num_words=1000)#Creates a tokenizer, configured to only take into account the 1,000 most common words
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
sequences

[[10,
  21,
  77,
  12,
  1,
  662,
  8,
  240,
  581,
  14,
  414,
  6,
  1,
  11,
  61,
  423,
  29,
  67,
  2,
  44,
  6,
  77,
  5,
  128,
  75,
  766,
  94,
  116,
  2,
  24,
  452,
  1,
  94,
  17,
  47,
  7,
  30,
  7,
  1,
  513,
  2,
  24,
  126,
  452,
  6,
  46,
  1,
  108,
  116,
  6,
  296,
  36,
  3,
  399,
  4,
  22,
  3,
  6,
  44,
  185,
  75,
  5,
  361],
 [10,
  21,
  1,
  108,
  827,
  126,
  5,
  307,
  101,
  115,
  4,
  206,
  7,
  227,
  861,
  13,
  8,
  9,
  1,
  108,
  3,
  2,
  13,
  408,
  767,
  4,
  269,
  5,
  4,
  258,
  8,
  11,
  18,
  9,
  1,
  116,
  9,
  3,
  101,
  89,
  795,
  5,
  6,
  12,
  148,
  111,
  3,
  121,
  469,
  5,
  1,
  201,
  23,
  8,
  9,
  231,
  2,
  174,
  139,
  17,
  33,
  19,
  27,
  177,
  5,
  92,
  93,
  123,
  12,
  8,
  78,
  114,
  8,
  9,
  1,
  55,
  26,
  13,
  2,
  191,
  44,
  28,
  172,
  153],
 [10,
  21,
  351,
  8,
  827,
  9,
  18,
  362,
  116,
  7,
  30,
  54,
  930,
  162,
  1,
  7,
  7,
  87,
  30,
  1,


In [0]:
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary') #for make matrix one hot coding
print(one_hot_results)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [0]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 13143 unique tokens.


### Listing 6.7 Using an Embedding layer

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Embedding

model = Sequential()
model.add(Embedding(10000, 8, input_length=20))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()
history = model.fit(samples ,
epochs=10,batch_size=32,validation_split=0.2)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


ValueError: ignored

In [0]:
!unzip "/content/drive/My Drive/1305_800230_bundle_archive.zip"

Archive:  /content/drive/My Drive/1305_800230_bundle_archive.zip
  inflating: test.ft.txt.bz2         
  inflating: train.ft.txt.bz2        


In [0]:
!mkdir source_data #ak new dir banai google drive par 
!mv train.ft.txt.bz2 source_data
!mv test.ft.txt.bz2 source_data

In [0]:
import numpy as np 
import pandas as pd 
import bz2
import gc
import chardet
import re
import os
print(os.listdir("/content/source_data"))

['test.ft.txt.bz2', 'train.ft.txt.bz2']


In [0]:
# Load the training data 
data = bz2.BZ2File("/content/source_data/train.ft.txt.bz2")
data = data.readlines()
data = [x.decode('utf-8') for x in data]
print(len(data)) 


3600000


In [0]:
data[1:5]

["__label__2 The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny.\n",
 '__label__2 Amazing!: This soundtrack is my favorite music of all time, hands down. The intense sadness of "Prisoners of Fate" (which means all the more if you\'ve played the game) and the hope in "A Distant Promise" and "Girl who Stole the Star" have been an important inspiration to me personally throughout my teen years. The higher energy tracks like "Chrono Cross ~ Time\'s Scar~", "Time of the Dreamwatch", and "Chronomantique" (indefinably remeniscent of Chrono Tri

In [1]:
!unzip "drive/My Drive/aclImdb"

Streaming output truncated to the last 5000 lines.
  inflating: aclImdb/train/pos/7755_9.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7755_9.txt  
  inflating: aclImdb/train/pos/7756_10.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7756_10.txt  
  inflating: aclImdb/train/pos/7757_9.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7757_9.txt  
  inflating: aclImdb/train/pos/7758_7.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7758_7.txt  
  inflating: aclImdb/train/pos/7759_10.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7759_10.txt  
  inflating: aclImdb/train/pos/775_7.txt  
  inflating: __MACOSX/aclImdb/train/pos/._775_7.txt  
  inflating: aclImdb/train/pos/7760_10.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7760_10.txt  
  inflating: aclImdb/train/pos/7761_10.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7761_10.txt  
  inflating: aclImdb/train/pos/7762_8.txt  
  inflating: __MACOSX/aclImdb/train/pos/._7762_8.txt  
  inflating: aclImdb/train/pos/7763_8.txt  
  inflat

### Listing 6.8 Processing the labels of the raw IMDB data

In [0]:
#read file data
import os
imdb_dir = 'aclImdb'#directroy of data
train_dir = os.path.join(imdb_dir, 'train')
labels = []
texts = []
for label_type in ['neg', 'pos']: #read positive and nagitive review separate
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name): #get all files in the folder
        if fname[-4:] == '.txt': #make sure file name ends with txt
            f = open(os.path.join(dir_name, fname),encoding="utf8")
            texts.append(f.read()) # append data read from file into text
            f.close()
            if label_type == 'neg': # if this is a nagative review
                labels.append(0)
        else: #if this is apositive review
            labels.append(1)

In [0]:
import numpy as np
timesteps = 100
input_features = 32
output_features = 64

inputs = np.random.random((timesteps, input_features))
state_t = np.zeros((output_features,))
W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features,))

successive_outputs = []

for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    successive_outputs.append(output_t)
    state_t = output_t
final_output_sequence = np.concatenate(successive_outputs, axis=0)

In [0]:
output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)

In [5]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN
model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32))
model.summary()

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 32)                2080      
Total params: 322,080
Trainable params: 322,080
Non-trainable params: 0
_________________________________________________________________
