<a href="https://colab.research.google.com/github/bilal444hammas/ASSIGNMENT-CH6/blob/master/EMG_Data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
df_EMG = pd.read_csv("/content/EMG-data.csv")
df_EMG.head()

time  channel1  channel2  channel3  ...  channel7  channel8  class  label
0     1   0.00001  -0.00002  -0.00001  ...   0.00000  -0.00001    0.0    1.0
1     5   0.00001  -0.00002  -0.00001  ...   0.00000  -0.00001    0.0    1.0
2     6  -0.00001   0.00001   0.00002  ...  -0.00001   0.00001    0.0    1.0
3     7  -0.00001   0.00001   0.00002  ...  -0.00001   0.00001    0.0    1.0
4     8  -0.00001   0.00001   0.00002  ...  -0.00001   0.00001    0.0    1.0

[5 rows x 11 columns]

In [ ]:
df_EMG.columns

Index(['time', 'channel1', 'channel2', 'channel3', 'channel4', 'channel5',
       'channel6', 'channel7', 'channel8', 'class', 'label'],
      dtype='object')

In [ ]:
df_EMG["class"].unique() 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6., nan])

In [ ]:
df_EMG["label"].unique() 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., nan])

In [ ]:
df_EMG["label"].value_counts()

2.0     136426
7.0     132640
9.0     127647
1.0     121170
8.0     117948
10.0    117682
4.0     114198
5.0     107248
3.0     105785
6.0      99619
Name: label, dtype: int64

In [ ]:
df_EMG["class"].value_counts()

0.0    774562
1.0     68449
5.0     68183
4.0     68154
3.0     67736
6.0     66970
2.0     66309
Name: class, dtype: int64

In [ ]:
labels = df_EMG["label"]

In [ ]:
labels

0           1.0
1           1.0
2           1.0
3           1.0
4           1.0
           ... 
1180359    10.0
1180360    10.0
1180361    10.0
1180362    10.0
1180363     NaN
Name: label, Length: 1180364, dtype: float64

In [ ]:
text_features = df_EMG.drop(columns=["label"])

In [ ]:
text_features.head()

time  channel1  channel2  channel3  ...  channel6  channel7  channel8  class
0     1   0.00001  -0.00002  -0.00001  ...  -0.00001   0.00000  -0.00001    0.0
1     5   0.00001  -0.00002  -0.00001  ...  -0.00001   0.00000  -0.00001    0.0
2     6  -0.00001   0.00001   0.00002  ...  -0.00002  -0.00001   0.00001    0.0
3     7  -0.00001   0.00001   0.00002  ...  -0.00002  -0.00001   0.00001    0.0
4     8  -0.00001   0.00001   0.00002  ...  -0.00002  -0.00001   0.00001    0.0

[5 rows x 10 columns]

In [ ]:
labels.shape

(1180364,)

In [ ]:
text_features.shape

(1180364, 10)

In [ ]:
labels = np.ravel(labels)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

labels = le.fit_transform(labels)
labels

array([ 0,  0,  0, ...,  9,  9, 10])

In [ ]:
# spliting data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(text_features, labels, test_size=0.2, random_state=1)

In [ ]:
x_train.shape # input shape

(944291, 10)

In [ ]:
y_train.shape

(944291,)

In [ ]:
models = tf.keras.Sequential
layers = tf.keras.layers

model = models([layers.Dense(512,activation="relu",input_shape=(10,)),
                layers.Flatten(),
                layers.Dense(64,activation="relu"),
                layers.Dense(32,activation="relu"),
                layers.Dense(40, activation='softmax')])

model.compile(optimizer="adam", 
             loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])

history = model.fit(x_train,y_train,epochs=20,validation_split=(0.0))

Epoch 1/20
29510/29510 [==============================] - 48s 2ms/step - loss: nan - accuracy: 0.1029
Epoch 2/20
  950/29510 [..............................] - ETA: 45s - loss: nan - accuracy: 0.1035